### PR TITLE
(maint) Release prep for 1.2.0

### PR DESCRIPTION
**Pull request by justinstoller**

### CODE REVIEW

**Comment by Magisus** [comment]
If we want to release this as 1.2.0, I think we also need to update the SNAPSHOT version in project.clj.

**Comment by justinstoller** [comment]
Yeah, good catch, I always forget that it's the version it bumps to (the opposite of our Ruby release job).

**Comment by Magisus** [comment]
Yeah I kind of hate it.

**Comment by justinstoller** [comment]
Updated

**Pull request merged**
