### PR TITLE
(TK-436) Add support for appending registry settings

### PR DESCRIPTION
**Pull request by jpinsonault**
This commits changes the behavior of initialize-registry-settings to allow it
to be called more than once for one domain, allowing multiple services to add
in the metrics they would like to whitelist for their domain.

As before, the first call will create the settings. Additional calls with the
same domain will merge and append the new settings to the old settings.

Since the only registry setting is currently :default-metrics-allowed, this
allows multiple TK services to call this service function, adding in their own
list of allowed metrics. Before, only one call could be made per domain, which
meant that you would have to designate a service to be the one that knows about
the list of metrics and initialize them.

### CODE REVIEW

**Comment by jpinsonault** [comment]
The name `initialize-registry-settings` doesn't seem good anymore. Maybe just `update-registry-settings`?

Also the behavior of merging the two maps together with `concat` as the way of resolving conflicts works fine right now, since the only setting is a list, and we have the schema to validate what comes out the other end. But if we ever introduce a different kind of setting that can't be combined using `concat` we'll have to revise the function a bit. 

I don't know if that matters right now though.

**Comment by jpinsonault** [comment]
ping @camlow325 @rlinehan for review when you get a chance

**Comment by rlinehan** [comment]
I'm good with this as-is - I feel like the comment indicates what it's doing right now and it seems reasonably obvious that that would need to be changed in the future.

I'm 👍 on having the new name be `update-registry-settings`.

**Comment by jpinsonault** [comment]
Pushed some commits to rename `initialize-registry-settings` in code and docs.
Updated the blurb in the docs about the `update-registry-settings` service fn
Rebased to fix merge conflict

**Comment by camlow325** [comment]
I might have been more averse to having the `initialize-registry-settings` function dropped entirely if anything outside of PE Puppet Server had been using it.  Doesn't look like that's the case, though, so I'm 👍 on the `update-registry-settings` name.

**Comment by jpinsonault** [comment]
Ha, sorry @camlow325 I guess I jumped the gun on changing the name

**Pull request merged**
