### PR TITLE
(maint) Bump ring-middleware dependency and prep for 0.4.1 release

### PR DESCRIPTION
**Pull request by rlinehan**

### CODE REVIEW

**Comment by rlinehan** [comment]
the only thing I'm hesitant about having this be a z release is that that version of ring-middleware is not backwards compatible. so if you pull in this version, all of your stuff will need to be updated to use ring-middleware 1.0.0.

**Comment by cprice404** [comment]
@rlinehan what would we even call it if we were worried about that though?  1.0.0?

I think we should probably just suck it up on this one and be clear in the announcement email.  And then we should try to get in the API fixes that we want, soon-ish, and do a 1.0.0 release, and then be more cautious about semver from there on out?

**Comment by rlinehan** [comment]
Yeah, I have no idea, just slightly nervous about it. That sounds good to me.

**Comment by cprice404** [comment]
+1

**Comment by jpinsonault** [comment]
👍

**Pull request merged**
