### PR TITLE
(MAINT) Update changelog for 0.3.0 release

### PR DESCRIPTION
**Pull request by jpinsonault**

### CODE REVIEW

**Comment by haus** [comment]
@jpinsonault i'm not sure adding a new library dependency should happen in a z release.

**Comment by jpinsonault** [comment]
@haus Yeah that's a good point

**Comment by jpinsonault** [comment]
Bumped it up to 0.3.0 and updated the changelog

**Comment by haus** [comment]
👍

**Comment by rlinehan** [comment]
👍 (although I changed the PR title to reflect the version)

**Pull request merged**
