### PR TITLE
(maint) Update Jolokia to 1.7.0

### PR DESCRIPTION
**Pull request by Sharpie**

### CODE REVIEW

**Comment by Magisus** [comment]
Did something in particular prompt this?

**Comment by mwaggett** [comment]
yeah @Sharpie it would be great if you could update the commit message to include why we're making this bump, even if it's just for staying up to date.

**Comment by Sharpie** [comment]
It's just for staying up to date.

The release notes also mention some cleanup of reflective access that could be good to pull in now that we're on Java 11.

**Comment by mwaggett** [comment]
@Sharpie could you please add that info to the commit message?

**Comment by Sharpie** [comment]
Commit message update.

**Review by mwaggett — APPROVED** [review]

**Pull request merged**
