### PR TITLE
(PE-31012) Update to latest clj-parent

### PR DESCRIPTION
**Pull request by barriserloth**
This picks up an update to ring-parent which mitigates a known
vulnerability in commons-fileupload.

### CODE REVIEW

**Review by mwaggett — APPROVED** [review]

**Comment by barriserloth** [comment]
Oh dear, looks like travis is failing because the version of lein isn't new enough? I can update that in .travis.yml

**Comment by Magisus** [comment]
You'll need to update Travis' lein version to 2.9.1, and while you're in there, we've been getting rid of the scripts that are just `lein test` and just inlining them.

**Review by mwaggett — APPROVED** [review]

**Comment by barriserloth** [comment]
I updated just the lein version before seeing Maggie's comment, sorry for the back-to-back force pushes but the script stuff should be cleaned up now 👍

**Comment by Magisus** [comment]
Hmm looks like we might need a test update? @austb might know something about that.

**Comment by Magisus** [comment]
The test is here https://github.com/puppetlabs/trapperkeeper-metrics/blob/main/test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj#L125-L140. I'm not totally sure why it's failing, it doesn't look like we necessarily configure tk-auth in that part...

**Comment by barriserloth** [comment]
I've been trying to figure it out locally but I kind of have no clue what I'm doing 😅

**Comment by Magisus** [comment]
The stuff logged is a red herring unrelated to the failure.

I've tracked this down to a NullPointer while reading `org.eclipse.jetty.server.session:context=v2,id=0,type=sessionhandler`. No idea why yet, the exception itself is swallowed and the response only has the type, not the cause. Downgrading Jetty did not appear to fix it.

**Comment by Magisus** [comment]
The test fails with all recent dependency bumps. We're jumping from a 1.7 version of clj-parent to 4.6 here, which is a huge diff. I'll see if I can figure out how to make this test pass, but it seems unlikely to be a real issue.

**Comment by Magisus** [comment]
@Sharpie I know this is ancient history since the _epic_ PR where this test was added but... do you have any idea what's going on here? It seems to be that the error is thrown somewhere in Jolokia. Any ideas why a metric we got from `list` would error when queried with `read`?

**Comment by austb** [comment]
I was able to get the stack trace by editting some things in `jolokia.clj`
<details>git diff
<p>
```
--- a/src/clj/puppetlabs/trapperkeeper/services/metrics/jolokia.clj
+++ b/src/clj/puppetlabs/trapperkeeper/services/metrics/jolokia.clj
@@ -42,9 +42,9 @@
    ;; "true" causes a lot of useless error messages and backtraces to flood the
    ;; logs when 404 results are generated by requests for JMX items that
    ;; do not exist.
-   :debug "false"
+   :debug "true"
    ;; Don't include backtraces in error results returned by the API.
-   :allowErrorDetails "false"
+   :allowErrorDetails "true"
    ;; Used by jolokia-access to match IPv4 and IPv6 to "localhost"
    :allowDnsReverseLookup "true"
    ;; Load access policy from: resources/jolokia-access.xml
 ```
 </p>
 </details>
but it's not really helping me yet.
 ```
2021-01-29 15:01:16,543 ERROR [p.t.s.m.jolokia] Error 500
java.lang.NullPointerException: null
        at org.eclipse.jetty.http.HttpFields.hashCode(HttpFields.java:1064)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.containsKey(HashMap.java:596)
        at java.util.HashSet.contains(HashSet.java:204)
        at org.jolokia.converter.json.ObjectSerializationContext.alreadyVisited(ObjectSerializationContext.java:64)
        at org.jolokia.converter.json.ObjectToJsonConverter.checkForLimits(ObjectToJsonConverter.java:313)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:162)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.CollectionExtractor.extractListAsJson(CollectionExtractor.java:99)
        at org.jolokia.converter.json.CollectionExtractor.extractObject(CollectionExtractor.java:61)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.ArrayExtractor.extractArray(ArrayExtractor.java:114)
        at org.jolokia.converter.json.ArrayExtractor.extractObject(ArrayExtractor.java:65)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:179)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.BeanExtractor.extractJsonifiedPropertyValue(BeanExtractor.java:200)
        at org.jolokia.converter.json.BeanExtractor.extractBeanValues(BeanExtractor.java:168)
        at org.jolokia.converter.json.BeanExtractor.exctractJsonifiedValue(BeanExtractor.java:155)
        at org.jolokia.converter.json.BeanExtractor.extractObject(BeanExtractor.java:89)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.MapExtractor.extractMapValues(MapExtractor.java:76)
        at org.jolokia.converter.json.MapExtractor.extractObject(MapExtractor.java:65)
        at org.jolokia.converter.json.ObjectToJsonConverter.callHandler(ObjectToJsonConverter.java:330)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObject(ObjectToJsonConverter.java:181)
        at org.jolokia.converter.json.ObjectToJsonConverter.extractObjectWithContext(ObjectToJsonConverter.java:207)
        at org.jolokia.converter.json.ObjectToJsonConverter.convertToJson(ObjectToJsonConverter.java:111)
        at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:443)
        at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)
        at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)
        at org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86)
        at org.jolokia.http.AgentServlet$4.handleRequest(AgentServlet.java:470)
        at org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:350)
        at org.jolokia.http.AgentServlet.handle(AgentServlet.java:321)
        at org.jolokia.http.AgentServlet.doGet(AgentServlet.java:277)
        at puppetlabs.trapperkeeper.services.metrics.jolokia.proxy$org.jolokia.http.AgentServlet$ff19274a.doGet(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at puppetlabs.trapperkeeper.services.metrics.jolokia.proxy$org.jolokia.http.AgentServlet$ff19274a.service(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
        at puppetlabs.trapperkeeper.services.metrics.jolokia$create_servlet$fn__30360$fn__30362.invoke(jolokia.clj:103)
        at clojure.core$proxy_call_with_super.invokeStatic(core_proxy.clj:388)
        at clojure.core$proxy_call_with_super.invoke(core_proxy.clj:384)
        at puppetlabs.trapperkeeper.services.metrics.jolokia$create_servlet$fn__30360.invoke(jolokia.clj:103)
        at puppetlabs.trapperkeeper.services.metrics.jolokia.proxy$org.jolokia.http.AgentServlet$ff19274a.service(Unknown Source)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:766)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.lang.Thread.run(Thread.java:748)
        ```

**Comment by Sharpie** [comment]
I'm not quite sure what's going on here either. It seems to have shown up between `clj-parent` 3.1.3 and 4.0.0 though. Oddly, we haven't seen something like this in released versions of Puppet Server or PuppetDB that are using `clj-parent` 4.x --- so it is likely specific to how the test is constructed.

**Comment by Sharpie** [comment]
Adding some `print` statements to the `doseq` in the test shows that it is failing when looping over some of the Jetty metrics:

```
org.eclipse.jetty.util.thread.strategy
context=HTTP_1_1@4ef08ab3,id=2,type=eatwhatyoukill
```

**Comment by Sharpie** [comment]
The test that is failing is basically a copy of an existing test for `metrics/v1/mbeans` that asserted each listable metric could be fetched in detail:

https://github.com/puppetlabs/trapperkeeper-metrics/blob/1.4.0/test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj#L117-L123

I recall being skeptical of this test's value when I first wrote it, but I was trying to match the coverage of the `metrics/v1` endpoint for the new `metrics/v2` endpoint. My guess as to what is going on here is that the `read` request is trying to fetch some Jetty context that only existed for the first `list` request and the newer version of Jetty doesn't handle that gracefully. This would also explain why we haven't seen it in the wild --- we haven't dug into metrics in `org.eclipse.jetty.util.thread.strategy` namespace when troubleshooting performance issues.

**Comment by Magisus** [comment]
Hm... So I guess we have a number of options:
1) Remove the test entirely
2) Squash the exception from this particular metric
3) Reduce the test case to just a "representative" case, i.e. choose a couple metrics we actually do tend to care about and query them.
4) something else?

(2) feels like the most in spirit with what this test was attempting to verify. We could explain what we think is happening in a comment. Gross but at least clear with the least loss of coverage. Unless people think we can actually fix the underlying issue?

**Comment by Sharpie** [comment]
I vote for door number 3: Reduce the test case to just a "representative" case as this problem seems specific to Jetty and not an issue with round-tripping in general. I think the test is a useful exercise that `/list` produces sane data and `/read` is working. Blocklisting just the Jetty metrics seems like it will set up a repeat of this test problem in the future.

Metrics under the `java.lang` namespace could be a good choice. There is a good variety with both statically named entries  and entries that are named dynamically depending on the garbage collection configuration. The metrics in this namespace are also built into the JVM and so shouldn't change as dependencies are changed in `project.clj`.

The diff would be:

```patch
diff --git a/test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj b/test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
index dc7917e..5419feb 100644
--- a/test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
+++ b/test/puppetlabs/trapperkeeper/services/metrics/metrics_service_test.clj
@@ -122,12 +122,12 @@
                  :let [resp (http-client/get (str "http://localhost:8180/metrics/v1" path))]]
            (is (= 200 (:status resp)))))

-       (let [resp (http-client/get "http://localhost:8180/metrics/v2/list")
+       (let [resp (http-client/get "http://localhost:8180/metrics/v2/list/java.lang")
              body (parse-response resp)]
          (is (= 200 (:status  resp)))
-         (doseq [[namesp mbeans] (get body "value") mbean (keys mbeans)
+         (doseq [mbean (keys (get body "value"))
                  :let [url (str "http://localhost:8180/metrics/v2/read/"
-                                (jolokia-encode (str namesp ":" mbean))
+                                (jolokia-encode (str "java.lang:" mbean))
                                 ;; NOTE: Some memory pools intentionally don't
                                 ;; implement MBean attributes. This results
                                 ;; in an error being thrown when those
```

**Comment by Magisus** [comment]
@barriserloth do you wanna make that update? Once that's done I think this can go in.

**Comment by barriserloth** [comment]
Yep, working on it now! Thanks for all the help

**Review by Magisus — APPROVED** [review]

**Pull request merged**
