### PR TITLE
(PE-36270) Update repo to use Jetty10

### PR DESCRIPTION
**Pull request by rileynewton**

### CODE REVIEW

**Comment by rileynewton** [comment]
Hmm no travis run..

**Comment by jonathannewman** [comment]
Travis has been disabled, we will need to add GitHub Actions.

**Comment by rileynewton** [comment]
Ah indeed PE-36363 has to be done first:
`Compiling 2 source files to /home/runner/work/trapperkeeper-metrics/trapperkeeper-metrics/target/classes
Syntax error (UnsupportedClassVersionError) compiling . at (ring/middleware/multipart_params.clj:54:20).
javax/servlet/http/HttpServletRequest has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Review by steveax — APPROVED** [review]
👍

**Pull request merged**
